import type Parser from "tree-sitter";

import { parseSource, type ParsedSource } from "../../graph/parsers/code-parser.js";
import type { AliasFact, AssignmentFact, BindingSeedFact, CallSiteFact, ConstructorFact, ContainmentScopeFact, DeclaredTypeAnnotationFact, ExpressionFact, FactLocalId, ImportFact, InheritanceFact, MemberFact, ModuleFact, NamespaceFact, ParameterFact, ParsedFactsBlob, ParsedSymbolFact, ReferenceFact, ReturnFact, SourceRangeFact } from "../facts.types.js";
import type { FactExtractionOutcome } from "../facts-extractor.js";
import type { LanguageFactExtractor, LanguageFactExtractorInput } from "../language-fact-extractor.js";

const range = (node: Parser.SyntaxNode): SourceRangeFact => ({ startLine: node.startPosition.row + 1, endLine: node.endPosition.row + 1, startColumn: node.startPosition.column, endColumn: node.endPosition.column });
const field = (node: Parser.SyntaxNode | null | undefined, name: string): Parser.SyntaxNode | undefined => node?.childForFieldName(name) ?? undefined;
const first = (node: Parser.SyntaxNode | undefined, types: readonly string[]): Parser.SyntaxNode | undefined => node?.namedChildren.find((child) => types.includes(child.type));
const id = (kind: string, number: number): FactLocalId => `${kind}:${number}` as FactLocalId;
const nameOf = (node: Parser.SyntaxNode | undefined): string | undefined => node?.text.split("::").at(-1)?.split(".").at(-1);
const declaratorName = (node: Parser.SyntaxNode | undefined): Parser.SyntaxNode | undefined => {
  if (!node) return undefined;
  if (["identifier", "field_identifier", "type_identifier"].includes(node.type)) return node;
  return declaratorName(field(node, "declarator") ?? node.namedChildren.at(-1));
};
const functionPointerSignature = (node: Parser.SyntaxNode, declarator: Parser.SyntaxNode | undefined): string | undefined => {
  const functionDeclarator = declarator?.descendantsOfType("function_declarator")[0];
  if (!functionDeclarator) return undefined;
  const returnType = field(node, "type")?.text ?? "";
  const parameters = field(functionDeclarator, "parameters")?.namedChildren.map((parameter) => field(parameter, "type")?.text ?? parameter.text) ?? [];
  return `${returnType}(${parameters.join(",")})`;
};
const diagnostics = (root: Parser.SyntaxNode): string[] => { const values: string[] = []; const visit = (node: Parser.SyntaxNode): void => { if (node.type === "ERROR" || node.isMissing) values.push(`${node.type}@${node.startPosition.row + 1}:${node.startPosition.column}`); for (const child of node.namedChildren) visit(child); }; visit(root); return [...new Set(values)].sort(); };

export function extractCFamilyTreeFacts(parsed: ParsedSource | undefined, input: LanguageFactExtractorInput): FactExtractionOutcome {
  try {
    if (!parsed) return { kind: "infrastructure_failure", error: new Error(`Unable to parse ${input.language} source`) };
    const symbols: ParsedSymbolFact[] = [], scopes: ContainmentScopeFact[] = [], imports: ImportFact[] = [], references: ReferenceFact[] = [], calls: CallSiteFact[] = [], bindings: BindingSeedFact[] = [], types: DeclaredTypeAnnotationFact[] = [], expressions: ExpressionFact[] = [], members: MemberFact[] = [], assignments: AssignmentFact[] = [], parameters: ParameterFact[] = [], returns: ReturnFact[] = [], constructors: ConstructorFact[] = [], inheritances: InheritanceFact[] = [], aliases: AliasFact[] = [], modules: ModuleFact[] = [], namespaces: NamespaceFact[] = [];
    const stack: FactLocalId[] = [], callableStack: ParsedSymbolFact[] = [], typeStack: ParsedSymbolFact[] = [], namespaceStack: string[] = [];
    const byName = new Map<string, ParsedSymbolFact[]>(); let sequence = 0;
    const next = (kind: string): FactLocalId => id(kind, ++sequence);
    const addScope = (node: Parser.SyntaxNode, kind: string, name?: string): FactLocalId => { const value = { localId: next("scope"), kind, name, parentId: stack.at(-1), range: range(node) }; scopes.push(value); stack.push(value.localId); return value.localId; };
    const addSymbol = (node: Parser.SyntaxNode, name: string, kind: ParsedSymbolFact["kind"], qualifiedName = [...namespaceStack, ...typeStack.map((item) => item.name), name].join("::")): ParsedSymbolFact => { const value = { localId: next("symbol"), name, kind, scopeId: stack.at(-1), declaredQualifiedName: qualifiedName, range: range(node) }; symbols.push(value); byName.set(name, [...(byName.get(name) ?? []), value]); return value; };
    const addExpression = (node: Parser.SyntaxNode, kind: ExpressionFact["kind"]): ExpressionFact => { const value = { localId: next("expression"), kind, text: node.text, ownerScopeId: stack.at(-1), range: range(node) }; expressions.push(value); return value; };
    const addBinding = (node: Parser.SyntaxNode, name: string, bindingKind: string, ownerId = stack.at(-1)): BindingSeedFact => { const value = { localId: next("binding"), name, bindingKind, ownerId, range: range(node) }; bindings.push(value); return value; };
    const typeText = (node: Parser.SyntaxNode | undefined): string | undefined => node?.text.replaceAll("const ", "").trim();
    const visit = (node: Parser.SyntaxNode): void => {
      const nodeName = nameOf(field(node, "name") ?? first(node, ["identifier", "type_identifier", "field_identifier", "namespace_identifier"]));
      const isNamespace = node.type === "namespace_definition";
      const isType = node.type === "class_specifier" || node.type === "struct_specifier" || node.type === "union_specifier" || node.type === "enum_specifier";
      const isCallable = node.type === "function_definition" || node.type === "function_declarator";
      const isScope = node.type === "translation_unit" || isNamespace || isType || node.type === "compound_statement";
      if (isScope) addScope(node, node.type, nodeName);
      if (isNamespace && nodeName) { namespaceStack.push(nodeName); const module = { localId: next("module"), name: nodeName, moduleKind: "namespace" as const, exported: false, range: range(node) }; modules.push(module); namespaces.push({ localId: next("namespace"), name: nodeName, ownerId: stack.at(-1), range: range(node) }); }
      let declared: ParsedSymbolFact | undefined;
      if (node.type === "preproc_include") { const pathNode = field(node, "path") ?? node.namedChildren.at(-1); if (pathNode) { let moduleSpecifier = pathNode.text; if ((moduleSpecifier.startsWith("<") && moduleSpecifier.endsWith(">")) || (moduleSpecifier.startsWith("\"") && moduleSpecifier.endsWith("\""))) moduleSpecifier = moduleSpecifier.slice(1, -1); imports.push({ localId: next("import"), moduleSpecifier, kind: "include", range: range(node) }); } }
      else if (isType && nodeName) { declared = addSymbol(node, nodeName, "class"); typeStack.push(declared); const base = field(node, "base_class_clause") ?? node.namedChildren.find((child) => child.type === "base_class_clause"); for (const item of base?.namedChildren ?? []) if (["type_identifier", "qualified_identifier", "template_type"].includes(item.type)) inheritances.push({ localId: next("inheritance"), subjectId: declared.localId, targetName: nameOf(item) ?? item.text, relationKind: "base", range: range(item) }); }
      else if (node.type === "type_definition" || node.type === "alias_declaration") { const target = field(node, "declarator") ?? field(node, "name"); if (target && nodeName) { const symbol = addSymbol(target, nodeName, "type"); aliases.push({ localId: next("alias"), aliasName: nodeName, targetName: field(node, "type")?.text ?? target.text, targetId: symbol.localId, aliasKind: "type", range: range(node) }); } }
      else if (node.type === "using_declaration") { const target = node.namedChildren[0]; if (target) aliases.push({ localId: next("alias"), aliasName: nameOf(target) ?? target.text, targetName: target.text, aliasKind: "namespace", range: range(node) }); }
      else if (node.type === "function_definition") { const declarator = field(node, "declarator"); const fn = declaratorName(declarator); if (fn) { const owner = typeStack.at(-1); declared = addSymbol(node, fn.text, owner ? "method" : "function", owner ? `${owner.declaredQualifiedName}::${fn.text}` : fn.text); callableStack.push(declared); if (owner) { members.push({ localId: next("member"), ownerSymbolId: owner.localId, memberName: fn.text, memberKind: "method", access: "instance", range: range(node) }); if (fn.text === owner.name) constructors.push({ localId: next("constructor"), ownerSymbolId: declared.localId, constructedTypeName: owner.name, range: range(node) }); } const returnType = field(node, "type"); if (returnType) returns.push({ localId: next("return"), ownerSymbolId: declared.localId, typeText: typeText(returnType), range: range(returnType) }); }
      } else if (node.type === "parameter_declaration" && callableStack.at(-1)) { const parameter = first(node, ["identifier", "field_identifier"]); if (parameter) { const binding = addBinding(parameter, parameter.text, "parameter", stack.at(-1)); parameters.push({ localId: next("parameter"), ownerSymbolId: callableStack.at(-1)!.localId, name: parameter.text, bindingId: binding.localId, typeText: field(node, "type")?.text, index: parameters.filter((item) => item.ownerSymbolId === callableStack.at(-1)!.localId).length, range: range(node) }); if (field(node, "type")) types.push({ localId: next("type"), ownerId: binding.localId, text: field(node, "type")!.text, range: range(field(node, "type")!) }); } }
      else if (node.type === "declaration" || node.type === "field_declaration") { const declarator = field(node, "declarator") ?? first(node, ["init_declarator", "pointer_declarator", "function_declarator"]); const identifier = declaratorName(declarator); if (identifier) { const owner = typeStack.at(-1); const symbol = addSymbol(node, identifier.text, "variable", owner ? `${owner.declaredQualifiedName}::${identifier.text}` : [...namespaceStack, identifier.text].join("::")); if (owner) members.push({ localId: next("member"), ownerSymbolId: owner.localId, memberName: identifier.text, memberKind: "field", access: "instance", range: range(node) }); const binding = addBinding(identifier, identifier.text, owner ? "member" : "local"); const declaredType = field(node, "type"); const pointerSignature = functionPointerSignature(node, declarator); if (declaredType) types.push({ localId: next("type"), ownerId: binding.localId, text: pointerSignature ? `function_pointer:${pointerSignature}` : declaredType.text, range: range(declaredType) }); const value = field(declarator, "value") ?? field(node, "value"); if (value) { const expression = addExpression(value, value.type === "call_expression" ? "call" : "identifier"); const sourceName = value.type === "call_expression" ? field(value, "function")?.text : value.type === "identifier" ? value.text : undefined; assignments.push({ localId: next("assignment"), targetId: binding.localId, sourceExpressionId: expression.localId, sourceName, assignmentKind: pointerSignature ? "function_pointer" : "declaration", range: range(node) }); if (value.type === "call_expression" || value.type === "argument_list") constructors.push({ localId: next("constructor"), constructedTypeName: value.type === "call_expression" ? field(value, "function")?.text ?? value.text : field(node, "type")?.text ?? identifier.text, callExpressionId: expression.localId, resultBindingId: binding.localId, range: range(value) }); } } }
      else if (node.type === "call_expression") { const fn = field(node, "function"); if (fn) { const expression = addExpression(fn, fn.type === "field_expression" ? "member" : "identifier"); calls.push({ localId: next("call"), calleeText: fn.text, callerId: callableStack.at(-1)?.localId, scopeId: stack.at(-1), range: range(node) }); if (fn.type === "field_expression") { const member = field(fn, "field") ?? fn.namedChildren.at(-1); const receiver = field(fn, "argument") ?? fn.namedChildren.at(0); if (member && receiver) members.push({ localId: next("member"), receiverId: addExpression(receiver, "identifier").localId, memberName: member.text, memberKind: "method", access: "instance", range: range(fn) }); } else references.push({ localId: next("reference"), name: fn.text, ownerId: callableStack.at(-1)?.localId, scopeId: stack.at(-1), range: range(fn) }); void expression; } }
      else if (node.type === "field_expression") { const member = field(node, "field") ?? node.namedChildren.at(-1); const receiver = field(node, "argument") ?? node.namedChildren.at(0); if (member && receiver && !node.parent?.type.includes("call_expression")) members.push({ localId: next("member"), receiverId: addExpression(receiver, "identifier").localId, memberName: member.text, memberKind: "property", access: "instance", range: range(node) }); }
      for (const child of node.namedChildren) visit(child);
      if (isCallable && declared) callableStack.pop();
      if (isType && declared) typeStack.pop();
      if (isNamespace && nodeName) namespaceStack.pop();
      if (isScope) stack.pop();
    };
    visit(parsed.tree.rootNode);
    const parserDiagnostics = diagnostics(parsed.tree.rootNode);
    const conditionalPreprocessorNodes = ["preproc_if", "preproc_ifdef", "preproc_else", "preproc_elif", "preproc_elifdef", "preproc_call", "preproc_def", "preproc_function_def"];
    for (const nodeType of conditionalPreprocessorNodes) for (const node of parsed.tree.rootNode.descendantsOfType(nodeType)) parserDiagnostics.push(`preprocessor_semantics:${node.type}@${node.startPosition.row + 1}`);
    if (input.language === "cpp" && parsed.tree.rootNode.descendantsOfType("template_declaration").length > 0) parserDiagnostics.push(`template_semantics@${parsed.tree.rootNode.descendantsOfType("template_declaration")[0]!.startPosition.row + 1}`);
    for (const item of symbols.filter((symbol) => symbol.kind === "function" || symbol.kind === "method")) { const binding = bindings.find((candidate) => candidate.name === item.name && candidate.bindingKind === "function"); if (!binding) bindings.push({ localId: item.localId, name: item.name, bindingKind: "function", ownerId: scopes[0]?.localId, range: item.range }); }
    modules.push({ localId: next("module"), name: input.filePath, moduleKind: "file", exported: false, range: range(parsed.tree.rootNode) });
    return { kind: "facts", facts: { factsSchemaVersion: input.factsSchemaVersion, factsVersion: input.factsVersion, contentHash: input.contentHash, language: input.language, parserIdentity: { language: parsed.adapter.language, ...parsed.adapter.metadata }, parseStatus: parserDiagnostics.length ? "deterministic_partial" : "complete", parserDiagnostics, symbols, containmentScopes: scopes, imports, exports: [], references, callSites: calls, bindingSeeds: bindings, declaredTypeAnnotations: types, expressions, members, assignments, parameters, returns, constructors, inheritances, implementations: [], aliases, modules, namespaces } };
  } catch (error) { return { kind: "infrastructure_failure", error: error instanceof Error ? error : new Error(String(error)) }; }
}

export function extractCFacts(input: LanguageFactExtractorInput): FactExtractionOutcome { if (input.language !== "c") return { kind: "infrastructure_failure", error: new Error(`Extractor c received ${input.language} input`) }; return extractCFamilyTreeFacts(parseSource(input.source, input.filePath, "c"), input); }
export const cFactExtractor: LanguageFactExtractor = { language: "c", extract: extractCFacts };
