import type { FactLocalId, ParsedFactsBlob, SourceRangeFact } from "../../../facts/facts.types.js";
import { symbolIdentity, type ModuleIdentity, type ScopeIdentity, type SymbolIdentity } from "../identities.js";
import type { AdapterContext, LanguageSemanticAdapter, SemanticCapabilities, SemanticEvidenceBatch, TypeRef } from "../types.js";

export const C_CAPABILITIES: SemanticCapabilities = { moduleImport: "partial", localBinding: "full", directCall: "full", declaredType: "full", constructorType: "partial", receiverMember: "partial", assignment: "full", parameterFlow: "partial", returnFlow: "partial", inheritance: "partial" };
export const CPP_CAPABILITIES: SemanticCapabilities = { moduleImport: "partial", localBinding: "full", directCall: "partial", declaredType: "partial", constructorType: "partial", receiverMember: "partial", assignment: "partial", parameterFlow: "partial", returnFlow: "partial", inheritance: "full" };
const empty = (): SemanticEvidenceBatch => ({ bindings: [], imports: [], exports: [], typeAnnotations: [], constructors: [], assignments: [], parameters: [], returns: [], members: [], inheritance: [], implementations: [], aliases: [], modules: [], calls: [], diagnostics: [] });

export function normalizeCFamilyFacts(facts: ParsedFactsBlob, context: AdapterContext): SemanticEvidenceBatch {
  const result = empty(), unit = context.sourceUnit, symbols = new Map(facts.symbols.map((item) => [item.localId, symbolIdentity({ repositoryId: context.repositoryIdentity.id, relativePath: unit.relativePath, language: unit.language, kind: item.kind, qualifiedName: item.declaredQualifiedName ?? item.name, discriminator: item.localId })]));
  const byName = new Map<string, SymbolIdentity[]>(); for (const item of facts.symbols) { const symbol = symbols.get(item.localId); if (symbol) byName.set(item.name, [...(byName.get(item.name) ?? []), symbol]); }
  const scopes = new Map(facts.containmentScopes.map((item) => [item.localId, item])); const scopeOf = (id: string | undefined): ScopeIdentity => ({ sourceUnit: unit, localId: id ?? facts.containmentScopes[0]?.localId ?? "scope:1", parentLocalId: id ? scopes.get(id as FactLocalId)?.parentId : undefined });
  const typeOf = (value: string | undefined): TypeRef | undefined => { if (!value) return undefined; const name = value.replaceAll("*", "").replaceAll("&", "").trim().split(" ").filter((part) => !["const", "struct", "class", "union", "enum"].includes(part)).join(" ").split("::").at(-1)!; const candidates = byName.get(name) ?? []; return candidates.length === 1 ? { kind: "known", symbol: candidates[0]! } : { kind: "named", name }; };
  const typeByBinding = new Map<string, TypeRef>(), functionPointerSignatureByBinding = new Map<string, string>(); for (const item of facts.declaredTypeAnnotations) { if (item.text.startsWith("function_pointer:")) functionPointerSignatureByBinding.set(item.ownerId, item.text.slice("function_pointer:".length)); else { const type = typeOf(item.text); if (type) typeByBinding.set(item.ownerId, type); } } for (const item of facts.constructors) if (item.resultBindingId) { const type = typeOf(item.constructedTypeName); if (type) typeByBinding.set(item.resultBindingId, type); }
  const functionSignature = (symbol: { discriminator: string }): string => { const returnType = facts.returns.find((item) => item.ownerSymbolId === symbol.discriminator)?.typeText ?? ""; const parameters = facts.parameters.filter((item) => item.ownerSymbolId === symbol.discriminator).sort((left, right) => left.index - right.index).map((item) => item.typeText ?? ""); return `${returnType}(${parameters.join(",")})`; };
  const base = (kind: string, localId: string, range: SourceRangeFact) => ({ evidenceId: `${unit.relativePath}:${kind}:${localId}` as never, sourceUnit: unit, range });
  for (const item of facts.bindingSeeds) result.bindings = [...result.bindings, { ...base("binding", item.localId, item.range), kind: "binding", scope: scopeOf(item.ownerId), name: item.name, bindingId: item.localId, declaredType: typeByBinding.get(item.localId) ?? ((byName.get(item.name)?.length === 1 && (facts.symbols.find((symbol) => symbol.localId === item.localId)?.kind === "function")) ? { kind: "known", symbol: byName.get(item.name)![0]! } : undefined) }];
  for (const item of facts.imports) result.imports = [...result.imports, { ...base("import", item.localId, item.range), kind: "import", specifier: item.moduleSpecifier, localName: item.localName, importedName: item.importedName, module: { repositoryId: context.repositoryIdentity.id, normalizedName: item.moduleSpecifier } satisfies ModuleIdentity }];
  for (const item of facts.modules) result.modules = [...result.modules, { ...base("module", item.localId, item.range), kind: "module", module: { repositoryId: context.repositoryIdentity.id, normalizedName: item.name, relativePath: unit.relativePath }, exportedNames: [] }];
  for (const item of facts.declaredTypeAnnotations) { const type = typeOf(item.text); if (type) result.typeAnnotations = [...result.typeAnnotations, { ...base("type", item.localId, item.range), kind: "type_annotation", subjectLocalId: item.ownerId, type }]; }
  for (const item of facts.constructors) result.constructors = [...result.constructors, { ...base("constructor", item.localId, item.range), kind: "constructor", constructedType: typeOf(item.constructedTypeName) ?? { kind: "named", name: item.constructedTypeName }, resultBindingId: item.resultBindingId }];
  for (const item of facts.assignments) { const candidates = item.sourceName ? (byName.get(item.sourceName) ?? []).filter((candidate) => candidate.kind === "function" || candidate.kind === "method") : []; const pointerSignature = functionPointerSignatureByBinding.get(item.targetId); if (item.assignmentKind === "function_pointer") { const compatible = candidates.filter((candidate) => functionSignature(candidate) === pointerSignature); if (facts.language === "cpp" && candidates.length > 1) result.diagnostics = [...result.diagnostics, { ...base("assignment", item.localId, item.range), code: "multiple_candidates", message: `C++ overload set for ${item.sourceName ?? ""} requires compiler overload resolution`, siteLocalId: item.localId }, { ...base("assignment", item.localId, item.range), code: "compiler_semantics_required", message: "C++ overload resolution is outside the structural floor", siteLocalId: item.localId }]; else if (compatible.length !== 1) result.diagnostics = [...result.diagnostics, { ...base("assignment", item.localId, item.range), code: "function_pointer_incompatible", message: `Function-pointer assignment ${item.sourceName ?? ""} does not match its AST signature`, siteLocalId: item.localId }]; else result.assignments = [...result.assignments, { ...base("assignment", item.localId, item.range), kind: "assignment", targetBindingId: item.targetId, sourceExpression: item.sourceExpressionId ? { sourceUnit: unit, localId: item.sourceExpressionId } : undefined, sourceType: { kind: "known", symbol: compatible[0]! } }]; } else result.assignments = [...result.assignments, { ...base("assignment", item.localId, item.range), kind: "assignment", targetBindingId: item.targetId, sourceExpression: item.sourceExpressionId ? { sourceUnit: unit, localId: item.sourceExpressionId } : undefined, sourceType: undefined }]; }
  for (const item of facts.parameters) { const callable = symbols.get(item.ownerSymbolId); if (callable) result.parameters = [...result.parameters, { ...base("parameter", item.localId, item.range), kind: "parameter", callable, index: item.index, bindingId: item.bindingId ?? item.localId, type: typeOf(item.typeText) }]; }
  for (const item of facts.returns) { const callable = symbols.get(item.ownerSymbolId); if (callable) result.returns = [...result.returns, { ...base("return", item.localId, item.range), kind: "return", callable, type: typeOf(item.typeText) }]; }
  for (const item of facts.members) { const owner = item.ownerSymbolId ? symbols.get(item.ownerSymbolId) : undefined; const receiver = item.receiverId ? facts.expressions.find((expression) => expression.localId === item.receiverId) : undefined; const receiverBinding = receiver ? facts.bindingSeeds.find((binding) => binding.name === receiver.text) : undefined; const ownerType = owner ? { kind: "known" as const, symbol: owner } : receiverBinding ? typeByBinding.get(receiverBinding.localId) : undefined; const candidate = owner ? owner : ownerType?.kind === "known" ? (byName.get(item.memberName) ?? []).find((symbol) => symbol.qualifiedName.startsWith(`${ownerType.symbol.qualifiedName}::`)) : undefined; if (ownerType && candidate) result.members = [...result.members, { ...base("member", item.localId, item.range), kind: "member", ownerType, memberName: item.memberName, member: candidate, access: item.access }]; else if (item.receiverId) result.diagnostics = [...result.diagnostics, { ...base("member", item.localId, item.range), code: "receiver_type_unknown", message: `C-family receiver is not statically known`, siteLocalId: item.localId }]; }
  for (const item of facts.inheritances) { const subject = symbols.get(item.subjectId); if (subject) result.inheritance = [...result.inheritance, { ...base("inheritance", item.localId, item.range), kind: "inheritance", subject, target: typeOf(item.targetName) ?? { kind: "named", name: item.targetName }, relation: item.relationKind }]; }
  for (const item of facts.aliases) result.aliases = [...result.aliases, { ...base("alias", item.localId, item.range), kind: "alias", alias: item.aliasName, targetName: item.targetName, target: typeOf(item.targetName) }];
  for (const item of facts.callSites) result.calls = [...result.calls, { ...base("call", item.localId, item.range), kind: "call", site: { sourceUnit: unit, localId: item.localId }, calleeName: item.calleeText, arguments: [] }];
  if (facts.language === "cpp" && facts.parserDiagnostics.some((item) => item.startsWith("template_semantics:"))) result.diagnostics = [...result.diagnostics, { ...base("language", "unsupported", facts.containmentScopes[0]?.range ?? { startLine: 1, endLine: 1 }), code: "compiler_semantics_required", message: "C++ templates are outside the structural floor" }];
  if (facts.parserDiagnostics.some((item) => item.startsWith("preprocessor_semantics:"))) result.diagnostics = [...result.diagnostics, { ...base("language", "preprocessor", facts.containmentScopes[0]?.range ?? { startLine: 1, endLine: 1 }), code: "preprocessor_semantics_required", message: "Preprocessor-dependent semantics are outside the structural floor" }];
  if (facts.parseStatus !== "complete" || facts.parserDiagnostics.length) result.diagnostics = [...result.diagnostics, { ...base("parse", "uncertain", facts.containmentScopes[0]?.range ?? { startLine: 1, endLine: 1 }), code: "parse_uncertain", message: facts.parserDiagnostics.join(", ") || "Tree-sitter reported an uncertain C-family parse" }];
  return result;
}

export const cFamilySemanticAdapter: LanguageSemanticAdapter = { adapterId: "c-family-phase14b", adapterVersion: 1, languages: ["c", "cpp"], capabilities: (language) => language === "c" ? C_CAPABILITIES : CPP_CAPABILITIES, normalizeFile: normalizeCFamilyFacts };
